version: '3.8'

services:
  # MySQL - Source database
  mysql:
    image: mysql:8.0
    container_name: youtube_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: youtube_data
      MYSQL_USER: etl_user
      MYSQL_PASSWORD: etl_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - etl_network

  # MinIO - Data Lake Storage
  minio:
    image: minio/minio
    container_name: youtube_minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio_user
      MINIO_ROOT_PASSWORD: minio_password
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Console
    volumes:
      - minio_data:/data
    networks:
      - etl_network

  # PostgreSQL - Target database for analytics
  postgres:
    image: postgres:15
    container_name: youtube_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: youtube_analytics
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - etl_network

  # Dagster - Orchestration
  dagster-webserver:
    build:
      context: .
      dockerfile: ./docker/dagster/Dockerfile
    container_name: youtube_dagster_webserver
    restart: always
    ports:
      - "3000:3000"
    environment:
      DAGSTER_HOME: /opt/dagster/dagster_home
      DAGSTER_POSTGRES_USER: postgres
      DAGSTER_POSTGRES_PASSWORD: postgres
      DAGSTER_POSTGRES_DB: dagster
      DAGSTER_POSTGRES_HOST: postgres
    volumes:
      - ./:/opt/dagster/app
      - dagster_home:/opt/dagster/dagster_home
    depends_on:
      - postgres
    networks:
      - etl_network

  # Dagster Daemon - Background processing
  dagster-daemon:
    build:
      context: .
      dockerfile: ./docker/dagster/Dockerfile
    container_name: youtube_dagster_daemon
    restart: always
    command: dagster-daemon run
    environment:
      DAGSTER_HOME: /opt/dagster/dagster_home
      DAGSTER_POSTGRES_USER: postgres
      DAGSTER_POSTGRES_PASSWORD: postgres
      DAGSTER_POSTGRES_DB: dagster
      DAGSTER_POSTGRES_HOST: postgres
    volumes:
      - ./:/opt/dagster/app
      - dagster_home:/opt/dagster/dagster_home
    depends_on:
      - postgres
    networks:
      - etl_network

networks:
  etl_network:
    driver: bridge

volumes:
  mysql_data:
  minio_data:
  postgres_data:
  dagster_home: